### ISSUE TITLE
time_of_flight_readout not working with qblox drivers

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#633] opened 2023-11-16 11:48 UTC
Hi,
I'm not sure if the problem is with the drivers or with qibocal routine, but I've tried running this routine with qblox and it does not work.
@PiergiorgioButtarini could you please check whether qblox driver supports these execution parameters:
```
acquisition_type=AcquisitionType.RAW,
averaging_mode=AveragingMode.CYCLIC,
```

**Comment by PiergiorgioButtarini** [comment] 2023-11-16 11:56
I think as of now Qblox doesn't support `AcquisitionType.RAW`. This believe is motivated both from the fact that there is no reference to this type of acquisition in qblox instruments, and also because the modules were always set with `hardware_demodulation == True`.

**Comment by andrea-pasquale** [comment] 2023-11-16 11:59
Thanks @PiergiorgioButtarini for checking. Could you please move this issue to `qibolab`? If a routine is not working for a driver related problem the issue should be opened in qibolab and not here.

**Comment by PiergiorgioButtarini** [comment] 2023-11-16 12:07
Sure, I will open an issue there.

**Comment by andrea-pasquale** [comment] 2023-11-20 09:39
Closing this as duplicate of https://github.com/qiboteam/qibolab/issues/663

**Closed by andrea-pasquale** 2023-11-20 09:39 UTC
