### ISSUE TITLE
Fitting crashes due to the absence of fit results.

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#86] opened 2022-09-30 09:48 UTC
Sometimes qq crashes if a routine tries to use a fitting result when none is available yet.
If the fitting data file is empty, `data_fit.df[param][0]` returns key error.
Thanks!
```python
    def update_platform_runcard(self, qubit, routine):

        try:
            data_fit = Data.load_data(
                self.folder, routine, self.format, f"fit_q{qubit}"
            )
        except:
            data_fit = Data()

        params = [i for i in list(data_fit.df.keys()) if "fit" not in i]
        settings = load_yaml(f"{self.folder}/platform.yml")

        for param in params:
            settings["characterization"]["single_qubit"][qubit][param] = int(
                data_fit.df[param][0]
            ) # FIXME: if none of the attempts of fitting succeed, the df is empty and it crashes here

        with open(f"{self.folder}/data/{routine}/platform.yml", "a+") as file:
            yaml.dump(
                settings, file, sort_keys=False, indent=4, default_flow_style=None
            )
```

**Comment by scarrazza** [comment] 2022-11-10 17:57
@andrea-pasquale could you please check this and close the issue if the problem is not reproducible or deprecated?

**Comment by andrea-pasquale** [comment] 2022-11-11 08:12
I think that this may be outdated. I've just tried to put an empty file as fitting output and the code does not crash anymore @scarrazza. I think that we can close this issue if you agree.

**Closed** 2022-11-14 05:40 UTC
Labels: bug

**Comment by aorgazf** [comment] 2022-11-14 05:41
@andrea-pasquale I guess we can close it and raise a new one if we see the problem again.

**Comment by andrea-pasquale** [comment] 2022-11-14 05:42
Sounds good to me @aorgazf.
