### ISSUE TITLE
Discrepancy between T2 routine with RT sweepers and using for lops

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#476] opened 2023-08-18 07:57 UTC
Hi, 
I have noticed a discrepancy between the results obtained running `t2` and `t2_sequences` on qw5q_gold_qblox:

![image](https://github.com/qiboteam/qibocal/assets/55031026/4259843c-6597-46b7-9484-77d14e8d5b90)

![image](https://github.com/qiboteam/qibocal/assets/55031026/ede810ed-50ae-4c7f-a8c7-f5a83c5d8410)

The problem may be in the driver.

**Comment by andrea-pasquale** [comment] 2023-08-24 09:56
I think that this might be related to the implementation of the sweeper in qblox.
With @igres26 we observed a similar behavior. It seems that the readout pulse at the end it is not pushed correctly.

**Comment by andrea-pasquale** [comment] 2023-11-21 11:18
Closing this as duplicate of https://github.com/qiboteam/qibolab/issues/650 (first bullet points).

**Closed by andrea-pasquale** 2023-11-21 11:18 UTC
Labels: bug, calibration
