### ISSUE TITLE
Closed loop calibration

### ISSUE THREAD

**Issue by wilkensJ** [qiboteam/qibocal#354] opened 2023-05-24 06:21 UTC
From the presentation in this issue: #352. 

More details
------------
A characterization can be used as a cost function to be minimized by an optimizer, for example Nelder Mead uses standard RB (the
gate fidelity) to fine tune the qubit frequency/pulse shape/…

Why
----
After the low level calibration routines, gate set level calibration routines have to be used to fine tune 1q and 2q gates, get rid of unwanted correlations in the chip, …

Suggestion
-----------
Define a pulse optimizer method/routine which optimizes (and/or updates)  a pulse parameter (e.g. pulse frequency) by minimizing a figure of merit from a characterization (e.g. gate fidelity). The pulse parameter which is being optimized has to be changed
on the fly or written to the (new) run card in each step.

<img width="255" alt="Bildschirmfoto 2023-05-24 um 08 16 14" src="https://github.com/qiboteam/qibocal/assets/70592365/942052f9-091b-4053-94bf-f5248d5476b4">

**Comment by andrea-pasquale** [comment] 2023-10-20 04:20
Closing this as duplicate of #497

**Closed by andrea-pasquale** 2023-10-20 04:20 UTC
