### ISSUE TITLE
qq plot repeats figures when not dependent on qubit

### ISSUE THREAD

**Issue by wilkensJ** [qiboteam/qibocal#174] opened 2022-12-07 18:12 UTC
When executing a protocol with several qubits but only one plot is being created, this plot is repeated as many times as there are qubits. Can this be made possible to surpassed? 

For example when running the crosstalk protocol on my branch ``jadwiga/rb_architecture`` #166 
 with ``qq runcards/crosstalkrb.yml``, and there are at least 2 qubits set, meaning ``qubits: [0, 1]`` and ``nqubits = 2`` for example, the report has the same plot two times.

<img width="513" alt="Bildschirmfoto 2022-12-07 um 18 07 46" src="https://user-images.githubusercontent.com/70592365/206261790-394fcc4d-314c-4712-89b8-7bb370bb29c0.png">

**Comment by andrea-pasquale** [comment] 2022-12-08 07:59
You are right @wilkensJ . This is happening because up to now in Qibocal every routine was designed to run only on single qubits.

**Comment by andrea-pasquale** [comment] 2023-09-26 14:25
I'm closing this as outdated. Moreover it is now possible to associate a single plot for multiple qubits. See for example https://github.com/qiboteam/qibocal/pull/452

**Closed as completed by andrea-pasquale** 2023-09-26 14:25 UTC
Labels: enhancement
